import {
  FullPuzzleData,
  buildGridMeta,
  computeGridSlots,
  getDayNumber,
  getPuzzleExpiry,
  parseGridStringTemplate,
} from '@crossword/shared';

export interface FallbackPuzzleDefinition {
  title: string;
  author: string;
  theme?: string;
  rawGrid: string[];
  solution: string[];
  clues: {
    across: Record<number, string>;
    down: Record<number, string>;
  };
}

/**
 * Served when no generated puzzle is available for a date. Every entry is a word from the
 * bundled word list, and the grid passes validateGridTemplate (see tests/fallback.test.ts).
 */
export const FALLBACK_PUZZLE_TEMPLATES: FallbackPuzzleDefinition[] = [
  {
    title: 'Daily Starter Crossword',
    author: 'Crossword Bot',
    rawGrid: [
      '...#...#....',
      '...#...#....',
      '............',
      '###...#...##',
      '....#...#...',
      '....#...#...',
      '...#...#....',
      '...#...#....',
      '##...#...###',
      '............',
      '....#...#...',
      '....#...#...',
    ],
    solution: [
      'FOE#HAS#BUNT',
      'YUM#ATE#INFO',
      'IRONCLADRULE',
      '###AKA#ADS##',
      'ICBM#NOD#APT',
      'SHOE#TIE#BEE',
      'EAR#GIN#GLEN',
      'EON#ACT#EELS',
      '##FEZ#MMA###',
      'LARGEHEARTED',
      'OREO#INN#ALE',
      'UTES#STY#OFF',
    ],
    clues: {
      across: {
        1: 'Adversary',
        4: 'Owns',
        7: 'Soft tap in baseball',
        11: '"Delicious!"',
        12: 'Had dinner',
        13: 'Details, for short',
        14: 'Regulation with no exceptions',
        17: 'Alias letters',
        18: 'Commercials',
        19: 'Long-range missile, briefly',
        22: 'Silent "yes"',
        24: 'Fitting',
        27: 'Sneaker or loafer',
        28: 'Draw',
        29: 'Spelling contest',
        30: 'Corn unit',
        31: 'Martini base',
        32: 'Secluded valley',
        33: 'Very long time',
        34: 'Play division',
        35: 'Snakelike swimmers',
        36: 'Tasseled cap',
        38: 'Cage-fighting sport, briefly',
        40: 'Generous and kind',
        46: 'Twist-apart cookie',
        47: 'Roadside lodging',
        48: 'Pub pour',
        49: 'Salt Lake City college athletes',
        50: 'Messy room, figuratively',
        51: 'Not on',
      },
      down: {
        1: 'Memo heading, briefly',
        2: 'Belonging to us',
        3: 'Moody rock genre',
        4: 'Clever shortcut',
        5: 'Ocean between Europe and the Americas',
        6: 'The Mediterranean, for one',
        7: 'Robin or wren',
        8: 'Out of order',
        9: 'Super Bowl org.',
        10: 'Foot digit',
        15: 'It goes on a tag at a mixer',
        16: 'Miami-___ County',
        19: '"Got it"',
        20: 'Elaine ___, two-time U.S. Cabinet secretary',
        21: '1966 film about Elsa the lioness',
        23: 'Soothing salve',
        25: 'Banana skin',
        26: 'Perfect scores, often',
        31: 'Steady look',
        32: 'Equipment',
        37: 'Senses of self',
        39: 'Lots of',
        40: 'Reed of the Velvet Underground',
        41: 'Gallery display',
        42: 'Not hers',
        43: 'The way, in Chinese philosophy',
        44: "Santa's helper",
        45: 'Excellent, in 1980s slang',
      },
    },
  },
  {
    title: 'Morning Warm-Up',
    author: 'Crossword Bot',
    rawGrid: [
      '....#...#...',
      '....#...#...',
      '....#...#...',
      '###...#...##',
      '...#...#....',
      '...#...#....',
      '....#...#...',
      '....#...#...',
      '##...#...###',
      '...#...#....',
      '...#...#....',
      '...#...#....',
    ],
    solution: [
      'SEAM#SEE#BIT',
      'KALE#OWL#ICE',
      'ITEM#REM#RYE',
      '###OWE#OLD##',
      'LET#ANT#AFRO',
      'ACE#DEW#BEEP',
      'WHAT#SOY#EAR',
      'SOME#SEA#DRY',
      '##SAW#DMS###',
      'ACT#RAG#TUSH',
      'SUE#AGE#ASIA',
      'HER#POD#GERM',
    ],
    clues: {
      across: {
        1: 'Line where two pieces of fabric meet',
        5: 'Spot with your eyes',
        8: 'Small piece',
        11: 'Leafy green in many smoothies',
        12: 'Nocturnal hooter',
        13: 'Rink surface',
        14: 'Entry on a list',
        15: 'Sleep stage with vivid dreams',
        16: 'Bread in a Reuben',
        17: 'Be in debt',
        19: 'Not new',
        21: 'Allow',
        24: 'Picnic pest',
        26: 'Rounded, voluminous hairstyle',
        29: 'Unreturnable serve',
        30: 'Morning moisture on grass',
        31: 'Microwave sound',
        32: '"Come again?"',
        34: 'Sauce for sushi',
        36: 'Listening organ',
        37: 'A few',
        38: 'Ocean',
        39: 'Not wet',
        40: "Carpenter's cutting tool",
        42: 'Private messages on Discord, briefly',
        44: 'Part of a play',
        46: 'Cleaning cloth',
        48: 'Rear end, informally',
        52: 'Take to court',
        53: 'Number of candles on a birthday cake, often',
        54: 'Largest continent',
        55: 'Not him',
        56: 'Pea holder',
        57: 'Microbe',
      },
      down: {
        1: 'Glide down a slope',
        2: 'Have a meal',
        3: 'Pub order',
        4: 'Office note',
        5: 'Ache after a hard workout',
        6: 'Female sheep',
        7: 'Red Sesame Street Muppet',
        8: 'Seed scattered for sparrows',
        9: 'Frozen over',
        10: 'Golf ball stand',
        18: 'Rolled-up bundle of cash',
        20: 'Science class room',
        21: 'Rules passed by a legislature',
        22: 'Sound that bounces back',
        23: 'Union truck driver',
        25: 'Cutting both ways, like some swords',
        27: 'Back',
        28: 'Grand Ole ___',
        33: 'Earl Grey, for one',
        35: 'Sweet potato relative',
        41: 'Tortilla sandwich',
        43: 'Male deer',
        44: 'Fireplace residue',
        45: 'Pool stick',
        47: 'In the past',
        49: 'Put to work',
        50: "Knight's title",
        51: 'Overacting performer',
      },
    },
  },
  {
    title: 'Power-Up',
    author: 'Crossword Bot',
    rawGrid: [
      '....#...#...',
      '....#...#...',
      '....#...#...',
      '###...#...##',
      '...#...#....',
      '...#...#....',
      '....#...#...',
      '....#...#...',
      '##...#...###',
      '...#...#....',
      '...#...#....',
      '...#...#....',
    ],
    solution: [
      'MARC#WIT#SPA',
      'OPAL#ACE#KIN',
      'MENU#RYE#YET',
      '###BOP#MAD##',
      'CAW#APT#WIGS',
      'OUR#FIE#EVAN',
      'WRIT#PEA#EGO',
      'SANE#END#RAW',
      '##GAS#ADS###',
      'OLD#WAG#UTAH',
      'FOR#AGE#NEMO',
      'FLY#MOD#KEPT',
    ],
    clues: {
      across: {
        1: 'Chagall who painted floating lovers',
        5: 'Clever humor',
        8: 'Place for a massage',
        11: 'October birthstone',
        12: 'Top card',
        13: 'Family members',
        14: 'Restaurant list',
        15: 'Whiskey grain',
        16: 'So far',
        17: 'Light tap on the head',
        19: 'Angry',
        21: "Crow's call",
        24: 'Well suited',
        26: 'Hairpieces',
        29: '"___ Town" (Thornton Wilder play)',
        30: '"___ on you!"',
        31: 'Actor Peters of "American Horror Story"',
        32: 'Court order',
        34: 'Pod resident',
        36: 'Sense of self',
        37: 'Of sound mind',
        38: 'Finish',
        39: 'Uncooked',
        40: 'Fuel for a car',
        42: 'Billboard messages',
        44: 'Aged',
        46: "Happy dog's tail motion",
        48: 'Beehive State',
        52: 'In favor of',
        53: 'Era',
        54: 'Clownfish of film',
        55: 'Travel by plane',
        56: 'Game add-on made by fans',
        57: 'Held on to',
      },
      down: {
        1: 'Mother, informally',
        2: 'Mimic',
        3: 'Jogged',
        4: 'Golf stick',
        5: 'Green tube Mario travels through',
        6: 'Slippery in winter',
        7: 'Be crowded',
        8: 'One who jumps from a plane',
        9: 'Apple dessert',
        10: 'Colony worker',
        18: 'Clumsy person',
        20: 'Wonder',
        21: 'Dairy herd',
        22: 'Distinctive atmosphere',
        23: 'Twist the water out of',
        25: 'Between 13 and 19 years old',
        27: 'Lady of pop',
        28: 'Winter blanket',
        33: 'Chai, for one',
        35: 'Sum up',
        41: 'Did laps in a pool',
        43: 'Underwater, as a ship',
        44: 'Not working, as a light',
        45: 'Chat reaction to a joke',
        47: 'Back in time',
        49: 'Casual shirt',
        50: "Guitarist's speaker",
        51: 'Scorching',
      },
    },
  },
  {
    title: 'Easy Does It',
    author: 'Crossword Bot',
    rawGrid: [
      '...#...#....',
      '...#...#....',
      '...#...#....',
      '##...#...###',
      '....#...#...',
      '....#...#...',
      '...#...#....',
      '...#...#....',
      '###...#...##',
      '....#...#...',
      '....#...#...',
      '....#...#...',
    ],
    solution: [
      'SAD#WOO#RICE',
      'PIE#OWL#ICON',
      'ADS#LED#TEND',
      '##OFF#SEA###',
      'GALA#STY#SHY',
      'IPAD#TEE#QUO',
      'LET#WAR#SULK',
      'AXE#HIS#KALE',
      '###FOR#SIR##',
      'OVAL#WET#EBB',
      'LINE#AWE#SOY',
      'DATA#YEW#TOE',
    ],
    clues: {
      across: {
        1: 'Down in the dumps',
        4: 'Court',
        7: 'Sushi staple',
        11: 'Thanksgiving dessert',
        12: 'Wise-looking bird',
        13: 'App symbol on a phone screen',
        14: 'Pop-ups, often',
        15: 'Guided',
        16: 'Take care of',
        17: 'Canceled',
        19: 'Mediterranean, for one',
        21: 'Fancy party',
        23: 'Pig pen',
        24: 'Bashful',
        27: 'Apple tablet',
        28: 'Driving range peg',
        29: 'Status ___',
        30: 'Rent out',
        31: 'Card game for two kids',
        32: 'Pout',
        33: "Lumberjack's tool",
        34: 'Belonging to him',
        35: 'Superfood green',
        36: 'On behalf of',
        37: 'Polite address',
        38: 'Egg shape',
        41: 'Soaked',
        43: 'Recede, as the tide',
        46: 'Queue',
        47: 'Amazement',
        48: 'Tofu source',
        49: 'Facts and figures',
        50: 'Evergreen tree',
        51: 'Piggy in a nursery rhyme',
      },
      down: {
        1: 'Resort with hot tubs',
        2: 'Help',
        3: 'Bleak and empty',
        4: 'Pack animal that howls',
        5: 'Have a tab',
        6: 'Senior citizens, informally',
        7: 'Moreno of "West Side Story"',
        8: 'Cooler contents',
        9: "Pro's opposite",
        10: 'Conclusion',
        18: 'Passing craze',
        20: 'Iris setting',
        21: '___ monster (venomous lizard)',
        22: 'Highest point',
        23: 'Flight of steps',
        24: 'Most old-fashioned',
        25: "Ship's body",
        26: 'Oxen harness',
        31: "Band behind \"Baba O'Riley,\" with \"The\"",
        32: 'Slalom need',
        36: 'Tiny jumping pest',
        37: 'Hearty one-pot meal',
        38: 'Antique',
        39: 'By way of',
        40: 'Hill dweller',
        42: "Lamb's mother",
        44: 'Jeer',
        45: 'Farewell',
      },
    },
  },
  {
    title: 'Snack Time',
    author: 'Crossword Bot',
    rawGrid: [
      '...#....#...',
      '...#....#...',
      '...#........',
      '....##...###',
      '###...##....',
      '........#...',
      '...#........',
      '....##...###',
      '###...##....',
      '........#...',
      '...#....#...',
      '...#....#...',
    ],
    solution: [
      'HAT#AMID#OFF',
      'ACE#MARE#WOO',
      'INN#PRISONER',
      'LETS##SKI###',
      '###PAD##LOBS',
      'BABYRUTH#DOT',
      'USE#CHEATDAY',
      'THEN##EYE###',
      '###ICY##AMEN',
      'WARTHOGS#APE',
      'AGO#OREO#MIX',
      'DEW#WELD#ACT',
    ],
    clues: {
      across: {
        1: 'Cap or beret',
        4: 'In the middle of',
        8: 'Away from work',
        11: 'Expert',
        12: 'Female horse',
        13: 'Try to win over',
        14: 'Bed-and-breakfast',
        15: 'Inmate',
        17: 'Allows',
        19: 'Winter sport item',
        20: 'Notepaper block',
        23: 'High, soft tosses',
        27: 'Candy bar with peanuts and nougat',
        32: 'Period',
        33: 'Utilize',
        34: 'Break from a strict diet',
        36: 'At that time',
        38: 'Look at',
        39: 'Frosty',
        42: 'Prayer ending',
        46: 'Tusked African pigs',
        51: 'Gorilla, for one',
        52: 'Previously',
        53: 'Cookie often dunked in milk',
        54: 'Blend',
        55: 'Mountain ___ (soda)',
        56: 'Join metal with heat',
        57: 'Pretend',
      },
      down: {
        1: 'Icy precipitation',
        2: 'Teen skin woe',
        3: 'Campsite shelter',
        4: 'Concert speaker',
        5: 'Scratch',
        6: 'Colored part of the eye',
        7: 'Office furniture',
        8: 'Possess',
        9: 'Enemy',
        10: 'In support of',
        16: 'Salad dressing ingredient',
        18: 'Secret agent',
        21: 'Rainbow shape',
        22: '"Obviously!"',
        24: 'Strange',
        25: 'Feathery scarf',
        26: 'Pigpen',
        27: 'However',
        28: 'Campfire leftover',
        29: 'Honey maker',
        30: 'Casual top',
        31: 'Barn bale material',
        35: 'Afternoon beverage',
        37: 'Tiny complaint',
        40: 'Food, slangily',
        41: 'Days of ___',
        43: '"___ Mia!"',
        44: 'Heroic tale',
        45: 'Following',
        46: 'Chewed gum lump',
        47: 'Get older',
        48: 'Paddle a boat',
        49: 'Hair product',
        50: 'Lawn starter',
      },
    },
  },
  {
    title: 'Curtain Call',
    author: 'Crossword Bot',
    rawGrid: [
      '...#....#...',
      '...#....#...',
      '........#...',
      '###...##....',
      '....##...###',
      '...#........',
      '........#...',
      '###...##....',
      '....##...###',
      '...#........',
      '...#....#...',
      '...#....#...',
    ],
    solution: [
      'PIN#USED#KIT',
      'ELF#ROAR#ICY',
      'ALLEGORY#LOP',
      '###BET##ZONE',
      'VERB##AGE###',
      'AYE#TURANDOT',
      'TEMPESTS#AWE',
      '###AXE##IDLE',
      'TINY##WIN###',
      'APE#PLANKTON',
      'MAR#EARN#EWE',
      'PDF#GYMS#ANT',
    ],
    clues: {
      across: {
        1: 'Bowling target',
        4: 'Secondhand',
        8: 'First-aid box',
        11: 'Workshop worker at the North Pole',
        12: "Lion's sound",
        13: 'Like winter roads',
        14: 'Story with a hidden meaning',
        16: 'Cut off, as branches',
        17: 'Wager',
        18: 'Time ___',
        19: 'Run or jump, grammatically',
        22: 'Stone ___',
        24: "Sailor's yes",
        25: 'Puccini opera featuring "Nessun dorma"',
        30: 'Violent storms',
        32: 'Reverence',
        33: 'Chop down',
        34: 'Not working',
        35: 'Minuscule',
        38: 'Victory',
        40: 'Chimp or orangutan',
        41: 'Food for a whale',
        46: 'Damage',
        47: 'Make, as money',
        48: 'Sheep in a flock',
        49: 'Document file type',
        50: 'Fitness centers',
        51: 'Tiny toiler',
      },
      down: {
        1: 'Green veggie in a pod',
        2: 'Sick',
        3: 'Org. with 32 teams',
        4: 'Strong desire',
        5: 'Chimney grime',
        6: 'Ability to hear music well',
        7: 'Like a desert',
        8: 'Metric weight, for short',
        9: 'Legend',
        10: 'Kind',
        15: 'Wane',
        18: 'Calm and centered',
        19: 'Big tub',
        20: 'Needle hole',
        21: 'Band behind "Losing My Religion"',
        22: 'Painting or sculpture',
        23: 'Stove fuel',
        25: '___-Mex',
        26: 'Employ',
        27: 'Father',
        28: 'Hooting bird',
        29: 'Where a golf hole begins',
        31: 'Salary',
        34: 'Tattoo',
        35: 'Pack down',
        36: 'Tablet from Apple',
        37: 'Foam ball brand',
        38: 'Toasty',
        39: 'Country hotels',
        41: 'Coat hook',
        42: 'Put down',
        43: 'Green or black drink',
        44: 'Have',
        45: 'Tennis court divider',
      },
    },
  },
  {
    title: 'Take Flight',
    author: 'Crossword Bot',
    rawGrid: [
      '...#....#...',
      '...#....#...',
      '........#...',
      '###...##....',
      '....##...###',
      '...#........',
      '........#...',
      '###...##....',
      '....##...###',
      '...#........',
      '...#....#...',
      '...#....#...',
    ],
    solution: [
      'MAT#REEF#APE',
      'OWE#IDLE#LED',
      'MEANTIME#SAG',
      '###OAT##POKE',
      'STOW##SHE###',
      'OWL#AVIATION',
      'YODELERS#DUO',
      '###YET##CORD',
      'TAME##ZOO###',
      'AXE#OVERBOOK',
      'ILL#DISC#FIE',
      'LET#DATA#FLY',
    ],
    clues: {
      across: {
        1: 'Yoga surface',
        4: 'Coral formation',
        8: 'Copy',
        11: 'Be indebted',
        12: 'Unemployed',
        13: 'Headed up',
        14: 'Interval between events',
        16: 'Droop',
        17: 'Granola grain',
        18: 'Hawaiian raw fish dish',
        19: 'Put away, as luggage',
        22: 'Not he',
        24: 'Night flier',
        25: 'The business of flying',
        30: 'Alpine singers',
        32: 'Pair',
        33: 'Still',
        34: 'Charging cable',
        35: 'Not wild',
        38: 'Wild animal park',
        40: "Firefighter's tool",
        41: 'Sell too many seats on, as a flight',
        46: 'Unwell',
        47: 'Frisbee, for one',
        48: '"For shame!"',
        49: 'Tennis serve do-over',
        50: 'Info',
        51: 'Soar',
      },
      down: {
        1: 'Parent',
        2: 'Wonderment',
        3: 'Kettle brew',
        4: '"Lovely ___, Meter Maid"',
        5: 'Revise',
        6: 'Shade tree',
        7: 'Charge',
        8: 'Too',
        9: 'Summit',
        10: 'Border',
        15: 'At this moment',
        18: 'Cat or dog',
        19: 'Edamame bean',
        20: 'Pair count',
        21: 'Stale',
        22: 'Mister',
        23: 'Owns',
        25: 'Brew',
        26: 'Animal doctor',
        27: 'Wedding vow',
        28: '"___ Gang" (classic film shorts)',
        29: 'Silent agreement',
        31: 'Hurricane center',
        34: 'Corn core',
        35: 'Kite part',
        36: 'Wheel rod',
        37: 'Thaw',
        38: 'Citrus peel',
        39: 'Killer whale',
        41: 'Unusual',
        42: 'Through',
        43: 'Percent ___ (sale sign)',
        44: 'Crude',
        45: 'Lock opener',
      },
    },
  },
];

export function createFallbackPuzzle(dateStr: string, index = 0): FullPuzzleData {
  const tpl = FALLBACK_PUZZLE_TEMPLATES[index % FALLBACK_PUZZLE_TEMPLATES.length];
  const grid = parseGridStringTemplate(tpl.rawGrid);
  const width = tpl.rawGrid[0]?.length || 12;
  const height = tpl.rawGrid.length || 12;
  const { cellNumbers, acrossSlots, downSlots } = computeGridSlots(grid, width, height);
  const gridMeta = buildGridMeta(grid, cellNumbers);

  const acrossClues = acrossSlots.map((slot) => ({
    number: slot.number,
    direction: 'across' as const,
    text: tpl.clues.across[slot.number] || `Clue for ${slot.number}-Across`,
    row: slot.row,
    col: slot.col,
    length: slot.length,
    answer: slot.cells.map((c) => tpl.solution[c.row][c.col]).join(''),
  }));

  const downClues = downSlots.map((slot) => ({
    number: slot.number,
    direction: 'down' as const,
    text: tpl.clues.down[slot.number] || `Clue for ${slot.number}-Down`,
    row: slot.row,
    col: slot.col,
    length: slot.length,
    answer: slot.cells.map((c) => tpl.solution[c.row][c.col]).join(''),
  }));

  const solutionGrid = tpl.solution.map((row) => row.split(''));

  return {
    id: `puzzle-${dateStr}`,
    date: dateStr,
    title: tpl.title,
    author: tpl.author,
    theme: tpl.theme,
    width,
    height,
    grid: gridMeta,
    clues: {
      across: acrossClues.map(({ answer, ...c }) => c),
      down: downClues.map(({ answer, ...c }) => c),
    },
    cluesWithAnswers: {
      across: acrossClues,
      down: downClues,
    },
    solution: solutionGrid,
    expiresAt: getPuzzleExpiry(dateStr).toISOString(),
    isClosed: false,
    status: 'published',
    createdAt: new Date().toISOString(),
  };
}

/**
 * The fallback puzzle for a date. Consecutive dates get consecutive puzzles, so the set repeats
 * only once every FALLBACK_PUZZLE_TEMPLATES.length days.
 */
export function getFallbackPuzzle(dateStr: string): FullPuzzleData {
  return createFallbackPuzzle(dateStr, getDayNumber(dateStr));
}
